site_name: farcaster-py documentation
repo_url: https://github.com/a16z/farcaster-py
site_url: https://a16z.github.io/farcaster-py
theme:
  name: "material"
  icon:
    logo: material/home
  favicon: images/favicon-32x32.png
  features:
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - navigation.footer
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple
      accent: deep orange

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: deep purple
      accent: deep orange
  logo: images/logo.png

plugins:
  - search
  - mkdocstrings
  - social

nav:
  - farcaster-py docs: index.md
  - reference.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/a16zcrypto
    - icon: fontawesome/brands/github 
      link: https://github.com/a16z
    - icon: material/web-box
      link: https://a16zcrypto.com/
  generator: false

copyright: Made with ❤️ by a16z crypto
